tabela=('Athletico Paranaense','Bahia','Flamengo','Bota Fogo','São Paulo','Cruzeiro','Atlético Mineiro','Red Bull Bragantino','Palmeiras','Internacional','Fortaleza','Grêmio','Vasco Da Gama','Criciúma','Juventude','Corinthians','Fluminense','Vitória','Atlético','Cuiabá')
print(f'a lista de times do brasileirão: {tabela}')
print ('=-=-='*20)
print(f'os 5 primeiros são: {tabela[:5]}')
print ('=-=-='*20)
print(f'os 4 últimos são: {tabela[16:]}')
print ('=-=-='*20)
print(f'os times em ordem alfabética: {sorted(tabela)}')
print ('=-=-='*20)
print ('o Chapecoense está em nenhuma colocação')